apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-spring-app
  labels:
    app: sample-spring-app
    env: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-spring-app
  template:
    metadata:
      labels:
        app: sample-spring-app
        env: dev
    spec:
      containers:
        - name: sample-spring-app
          image: bcrshared.azurecr.io/sample-spring-app
          ports:
            - name:  http
              containerPort: 8080
              protocol: TCP