name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master

        - uses: Azure/docker-login@v1
          with:
            login-server: bcrshared.azurecr.io
            username: ${{ secrets.ACR_USERNAME }}
            password: ${{ secrets.ACR_PASSWORD }}

        - run: |
            docker build . -t bcrshared.azurecr.io/sample-spring-app:${{ github.sha }}
            docker push bcrshared.azurecr.io/sample-spring-app:${{ github.sha }}

        # Set the target AKS cluster.
        - uses: Azure/aks-set-context@v1
          with:
            creds: '${{ secrets.AZURE_CREDENTIALS }}'
            cluster-name: qa-norwayeast-shared-aks
            resource-group: qa-norwayeast-rg

        # create an ImagePullSecret to push the image from a private ACR repository
        - uses: Azure/k8s-create-secret@v1
            with:
              container-registry-url: bcrshared.azurecr.io
              container-registry-username: ${{ secrets.ACR_USERNAME }}
              container-registry-password: ${{ secrets.ACR_PASSWORD }}
              secret-name: k8s-secret

        # deploy the application using the YAML manifests
        - uses: Azure/k8s-deploy@v1
            with:
              manifests: |
                manifests/deployment.yaml
                manifests/service.yaml
              images: |
                bcrshared.azurecr.io/sample-spring-app:${{ github.sha }}
              imagepullsecrets: |
                k8s-secret
